### PR TITLE
Improve Exercise Form Field Titles

### PR DESCRIPTION
**Pull request by duaanakshbandi**
This PR fixes https://github.com/Sapphire-CM/Sapphire/pull/585

Q: Does a Rspec / test make sense here?

### CODE REVIEW

**Comment by matthee** [comment]
Regarding your question: No, I don't think we need tests for changing table headers. 

IMHO tests should verify tasks critical tasks and data. If we were to break the table header in a future release, probably no-one would even notice for some time. Therefore, I think it is not worth to test those strings directly.

**Review by matthee — APPROVED** [review]
Looks good to me! All systems go!

One simple thing: Could you add the string "Fixes #585" to your PR description? When merging this PR, GitHub will autoclose this issue and leave a reference in the issue history to this PR. (Simply improves our workflow)

**Comment by duaanakshbandi** [comment]
Hello Matthias, thank you for your comments! ^^

I have updated the PR comment, hopefully this is what you mean, please let me know if I should change it elsewhere :)

**Comment by matthee** [comment]
Great! Thanks for your contribution!

**Pull request merged**
